apiVersion: v1
kind: Secret
metadata:
  name: laravel-app-secret
  namespace: ns-laravel-app
type: Opaque
stringData:
  password: "123"
  key: base64:P1kTFqfaHA/O9o3eA+4D4ipFNlooFIKBkBK0EAcb/Tc=
  rootpassword: root