apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-laravel
  namespace: ns-mysql
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  hostPath:
    path: "/data"  # Gantilah path ini sesuai dengan lingkungan Anda